name: Build container image

on:
  workflow_dispatch:
  workflow_call:
    # inputs:
    #   environment:
    #     type: string
    #     description: environment to deploy to
    #     required: true

jobs:
  build:
    runs-on: ubuntu-latest
    # environment: container
    steps:
      - name: Verify secrets
        run: |
          if [[ "${{ secrets.TEST }}" != "testxyz" ]]; then
            echo "Secret is not okay!"
            exit 1
          fi
          echo "Secret is okay!"
