name: Build container image

on:
  workflow_call:
    secrets:
      test:
        type: string
        required: false
    inputs:
      environment:
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Verify secrets
        run: |
          if [[ "${{ secrets.test }}" != "testxyz" ]]; then
            echo "Secret is not okay!"
            exit 1
          fi
          echo "Secret is okay!"
