name: Test caller

on:
  push:

jobs:

  cache:
    uses: ./.github/workflows/build.yaml
    secrets:
      test: ${{ secrets.TEST }}

  deploy:
    uses: ./.github/workflows/build.yaml
    with:
      environment: container
    secrets:
      test: ${{ secrets.TEST }}
